# SPDX-FileCopyrightText: 2026 Joshua Menezes and AlphEdge contributors
# SPDX-License-Identifier: MIT
"""Publish the holdings generated by the same backtests as the scenario cache."""
import json
from datetime import datetime, timezone
from pathlib import Path

from alpha_strategy.config import StrategyConfig
from alpha_strategy.data import download_history
from alpha_strategy.universe import get_constituent_universe, to_yahoo_symbol
from dashboard.explorer import _current_candidates
from jobs.build_scenarios import completed_sessions


def build():
    scenarios = json.loads(Path('state/scenarios.json').read_text())
    if scenarios.get('strategy_id') != 'hold-five-v1':
        raise RuntimeError('Historical scenarios have not been regenerated for hold-five-v1')
    cfg = StrategyConfig.from_yaml('config.yaml')
    universe = get_constituent_universe(cfg.index_universe, cache_dir=Path('cache'),
                                        max_age_days=cfg.universe_refresh_days)
    raw = completed_sessions(download_history(
        [to_yahoo_symbol(s) for s in universe] + [cfg.benchmark_ticker],
        years=2, cache_dir=cfg.data_cache_dir, refresh_days=0))
    ranking = _current_candidates(False, True, 15, prepared=raw, universe=universe)
    baskets = {'0/1/15': ranking}  # independent ranking, never a buy list
    for key, variant in scenarios['variants'].items():
        latest = variant['latest']
        if latest['date'] != ranking['date']:
            raise RuntimeError('Current baskets and historical scenario dates disagree')
        baskets[key] = {**latest, 'settings': {'key': key},
                        'method': 'Actual simulated basket at the latest close; weights include residual cash.'}
    payload = {'strategy_id': 'hold-five-v1',
               'computed_at': datetime.now(timezone.utc).isoformat(),
               'price_date': ranking['date'], 'baskets': baskets}
    path = Path('state/holdings_cache.json')
    temp = path.with_suffix('.json.tmp')
    temp.write_text(json.dumps(payload, allow_nan=False, separators=(',', ':')) + '\n')
    temp.replace(path)
    print(f"Cached {len(baskets)-1} model baskets through {payload['price_date']}")


if __name__ == '__main__':
    build()
